project_type = :stand_alone
http_path= "../"
css_dir = "css"
sass_dir = "sass"
images_dir = "img/"
javascripts_dir = "js"
fonts_dir = "fonts/"
line_comments = false
output_style = :compressed
relative_assets = true
